# shared/contracts/alert_event.py
"""
File Use:
    Defines the AlertEvent contract — high-level events generated by
    the Rule Engine when pipeline detections match alert conditions.

Implements:
    - AlertSeverity (enum for alert severity levels)
    - AlertEvent (pydantic model for generated alerts)

Depends On:
    - pydantic

Used By:
    - apps/event_processor/rule_engine.py
    - apps/api_service/routes/alerts.py
"""

from enum import StrEnum
from uuid import uuid4

from pydantic import BaseModel, Field


class AlertSeverity(StrEnum):
    """Severity levels for generated alerts."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(StrEnum):
    """Lifecycle status for an alert."""

    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class AlertEvent(BaseModel):
    """A high-level alert generated by the Rule Engine.

    Responsibilities:
        - Represent a meaningful event triggered by rule evaluation.
        - Link back to source frame, camera, and pipeline for traceability.
        - Carry severity and confidence for prioritization.
    """

    alert_id: str = Field(default_factory=lambda: str(uuid4()))
    tenant_id: str
    camera_id: str
    frame_id: str
    alert_type: str
    timestamp: float
    severity: AlertSeverity = AlertSeverity.MEDIUM
    confidence: float
    pipeline_id: str
    details: dict | None = None
    status: AlertStatus = AlertStatus.OPEN
    snapshot_path: str | None = None
    clip_path: str | None = None
