# shared/contracts/alert_event.py
"""
File Use:
    Defines the AlertEvent contract — high-level events generated by
    the Rule Engine when pipeline detections match alert conditions.

Implements:
    - AlertSeverity (enum for alert severity levels)
    - AlertEvent (pydantic model for generated alerts)

Depends On:
    - pydantic

Used By:
    - apps/event_processor/rule_engine.py
    - main.py
"""

from enum import StrEnum
from uuid import uuid4

from pydantic import BaseModel, model_validator


class AlertSeverity(StrEnum):
    """Severity levels for generated alerts."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(StrEnum):
    """Lifecycle status for an alert."""

    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class AlertEvent(BaseModel):
    """A high-level alert generated by the Rule Engine.

    alert_id format: {tenant_id}_{camera_id}_{12-char hex} — auto-generated
    so storage paths and logs are traceable to their origin.
    """

    alert_id: str = ""
    tenant_id: str
    camera_id: str
    frame_id: str
    alert_type: str
    timestamp: float
    severity: AlertSeverity = AlertSeverity.MEDIUM
    confidence: float
    pipeline_id: str
    details: dict | None = None
    status: AlertStatus = AlertStatus.OPEN
    snapshot_path: str | None = None
    clip_path: str | None = None

    @model_validator(mode="after")
    def _generate_alert_id(self) -> "AlertEvent":
        if not self.alert_id:
            self.alert_id = f"{self.tenant_id}_{self.camera_id}_{uuid4().hex[:12]}"
        return self
